// Generated by GDScript-transpiler
use godot::prelude::*;

#[derive(GodotClass)]
#[class(init, base=Node)]
struct Test {
    // TODO vars
    base: Base<Node>,
}

#[godot_api]
impl Test {
    #[func]
    fn test(&mut self, test_arg: i64) -> i64 {
        return 5;
    }
}
